export const SM_BREAKPOINT = 640;
export const MD_BREAKPOINT = 768;
export const MOBILE_BREAKPOINT = 768;
export const LG_BREAKPOINT = 1024;
export const XL_BREAKPOINT = 1280;

export const BREAKPOINT_LIST = [SM_BREAKPOINT, MD_BREAKPOINT, LG_BREAKPOINT, XL_BREAKPOINT];
